
# FIXME: This is work in progress and requires testing
# FIXME: Use workflow dispatch or environments for manual controls

on:
  push:
    branches:
      - main

jobs:

  package:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@main
      - run: ./execute package

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ package ]
    steps:
      - uses: actions/checkout@main
      - run: ./execute deploy dev

  deploy-stg:
    runs-on: ubuntu-latest
    needs: [ deploy-dev ]
    steps:
      - uses: actions/checkout@main
      - run: ./execute deploy stg

  deploy-prd:
    runs-on: ubuntu-latest
    needs: [ deploy-stg ]
    steps:
      - uses: actions/checkout@main
      - run: ./execute deploy prd
